import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { UI } from "~/cli/abstractions/UI.js";
import { Prompts } from "~/cli/abstractions/Prompts.js";
import { isCancelled } from "~/cli/abstractions/isCancelled.js";
import { InitCommand as Abstraction } from "./abstractions/InitCommand.js";

/**
 * The .env the CLI reads and writes, resolved when the command runs rather than when the module is
 * loaded. A constant captured at import time is the wrong file the moment the process changes
 * directory, and it is the one file here whose contents are not recoverable.
 */
function envPath(): string {
  return join(process.cwd(), ".env");
}

class InitCommandImpl implements Abstraction.Interface {
  public readonly name = "init";
  public readonly description = "Initialize project configuration (.env file)";

  public constructor(
    private readonly ui: UI.Interface,
    private readonly prompts: Prompts.Interface,
  ) {}

  public async execute(): Promise<void> {
    this.ui.intro("Initialize webiny-mock-data");

    const path = envPath();

    if (existsSync(path)) {
      const overwrite = await this.prompts.confirm({
        message: ".env file already exists. Overwrite?",
      });

      if (isCancelled(overwrite) || !overwrite) {
        this.ui.cancel("Cancelled — existing .env kept.");
        return;
      }
    }

    const apiPort = await this.prompts.text({
      message: "API server port",
      defaultValue: "4000",
      placeholder: "4000",
    });
    if (isCancelled(apiPort)) {
      this.ui.cancel("Cancelled.");
      return;
    }

    const uiPort = await this.prompts.text({
      message: "UI dev server port",
      defaultValue: "4001",
      placeholder: "4001",
    });
    if (isCancelled(uiPort)) {
      this.ui.cancel("Cancelled.");
      return;
    }

    const encryptionKey = randomBytes(32).toString("hex");

    const envContent = [
      "# webiny-mock-data configuration",
      "# Generated by: yarn cli init",
      "",
      "# Encryption key for API tokens stored in SQLite (do NOT share or commit)",
      `ENCRYPTION_KEY=${encryptionKey}`,
      "",
      "# Server ports",
      `API_PORT=${apiPort || "4000"}`,
      `UI_PORT=${uiPort || "4001"}`,
      "",
      "# How many jobs may run at once across every project. One running job per project is",
      "# enforced regardless, so this only binds with several projects active at the same time.",
      "MAX_CONCURRENT_JOBS=4",
      "",
      "# Optional: custom database path (default: .webiny/data-mock.db)",
      "# DB_PATH=./.webiny/data-mock.db",
      "",
    ].join("\n");

    writeFileSync(path, envContent, "utf-8");

    this.ui.log.success(".env file created with a fresh encryption key.");
    this.ui.log.info(`API port: ${apiPort || "4000"}, UI port: ${uiPort || "4001"}`);
    this.ui.outro("Run 'yarn cli add-project' to add your first Webiny project.");
  }
}

export const InitCommand = Abstraction.createImplementation({
  implementation: InitCommandImpl,
  dependencies: [UI, Prompts],
});
