import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { Command } from "~/cli/abstractions/Command.js";
import { UI } from "~/cli/abstractions/UI.js";
import { Prompts } from "~/cli/abstractions/Prompts.js";
import { isCancel } from "@clack/prompts";
import { InitCommand as Abstraction } from "./abstractions/InitCommand.js";

const ENV_PATH = join(process.cwd(), ".env");

class InitCommandImpl implements Abstraction.Interface {
  public readonly name = "init";
  public readonly description = "Initialize project configuration (.env file)";

  public constructor(
    private readonly ui: UI.Interface,
    private readonly prompts: Prompts.Interface,
  ) {}

  public async execute(): Promise<void> {
    this.ui.intro("Initialize webiny-mock-data");

    if (existsSync(ENV_PATH)) {
      const overwrite = await this.prompts.confirm({
        message: ".env file already exists. Overwrite?",
      });

      if (isCancel(overwrite) || !overwrite) {
        this.ui.cancel("Cancelled — existing .env kept.");
        return;
      }
    }

    const encryptionKey = randomBytes(32).toString("hex");

    const envContent = [
      "# webiny-mock-data configuration",
      "# Generated by: yarn cli init",
      "",
      "# Encryption key for API tokens stored in SQLite (do NOT share or commit)",
      `ENCRYPTION_KEY=${encryptionKey}`,
      "",
      "# Optional: custom database path (default: .webiny/data-mock.db)",
      "# DB_PATH=./.webiny/data-mock.db",
      "",
      "# Optional: custom API server port (default: 3001)",
      "# API_PORT=3001",
      "",
    ].join("\n");

    writeFileSync(ENV_PATH, envContent, "utf-8");

    this.ui.log.success(".env file created with a fresh encryption key.");
    this.ui.outro("Run 'yarn cli add-project' to add your first Webiny project.");
  }
}

export const InitCommand = Command.createImplementation({
  implementation: InitCommandImpl,
  dependencies: [UI, Prompts],
});
