import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import { UI } from "~/cli/abstractions/UI.js";
import { Prompts } from "~/cli/abstractions/Prompts.js";
import { isCancel } from "@clack/prompts";
import { InitCommand as Abstraction } from "./abstractions/InitCommand.js";

const ENV_PATH = join(process.cwd(), ".env");

class InitCommandImpl implements Abstraction.Interface {
  public readonly name = "init";
  public readonly description = "Initialize project configuration (.env file)";

  public constructor(
    private readonly ui: UI.Interface,
    private readonly prompts: Prompts.Interface,
  ) {}

  public async execute(): Promise<void> {
    this.ui.intro("Initialize webiny-mock-data");

    if (existsSync(ENV_PATH)) {
      const overwrite = await this.prompts.confirm({
        message: ".env file already exists. Overwrite?",
      });

      if (isCancel(overwrite) || !overwrite) {
        this.ui.cancel("Cancelled — existing .env kept.");
        return;
      }
    }

    const apiPort = await this.prompts.text({
      message: "API server port",
      defaultValue: "3001",
      placeholder: "3001",
    });
    if (isCancel(apiPort)) {
      this.ui.cancel("Cancelled.");
      return;
    }

    const uiPort = await this.prompts.text({
      message: "UI dev server port",
      defaultValue: "5173",
      placeholder: "5173",
    });
    if (isCancel(uiPort)) {
      this.ui.cancel("Cancelled.");
      return;
    }

    const encryptionKey = randomBytes(32).toString("hex");

    const envContent = [
      "# webiny-mock-data configuration",
      "# Generated by: yarn cli init",
      "",
      "# Encryption key for API tokens stored in SQLite (do NOT share or commit)",
      `ENCRYPTION_KEY=${encryptionKey}`,
      "",
      "# Server ports",
      `API_PORT=${(apiPort as string) || "3001"}`,
      `UI_PORT=${(uiPort as string) || "5173"}`,
      "",
      "# Optional: custom database path (default: .webiny/data-mock.db)",
      "# DB_PATH=./.webiny/data-mock.db",
      "",
    ].join("\n");

    writeFileSync(ENV_PATH, envContent, "utf-8");

    this.ui.log.success(".env file created with a fresh encryption key.");
    this.ui.log.info(
      `API port: ${(apiPort as string) || "3001"}, UI port: ${(uiPort as string) || "5173"}`,
    );
    this.ui.outro("Run 'yarn cli add-project' to add your first Webiny project.");
  }
}

export const InitCommand = Abstraction.createImplementation({
  implementation: InitCommandImpl,
  dependencies: [UI, Prompts],
});
